# Generated by Django 4.1.3 on 2023-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('uncos', 'Новости'), ('articles', 'Статьи')], default='uncos', max_length=10)),
                ('data_pub', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
