# Generated by Django 4.1.3 on 2023-07-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_category_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_category_ru',
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='datetime_post_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='datetime_post_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='header_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='header_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
