# Generated by Django 4.1.3 on 2023-07-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_category_name_category_en_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='category_en_us',
            field=models.CharField(choices=[('uncos', 'Новости'), ('articles', 'Статьи')], default='uncos', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='category_ru',
            field=models.CharField(choices=[('uncos', 'Новости'), ('articles', 'Статьи')], default='uncos', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='data_pub_en_us',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='data_pub_ru',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
