# Generated by Django 4.1.3 on 2023-07-14 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_new_category_en_us_new_category_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_name_en_us',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='user_name_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='user_rating_en_us',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='user_rating_ru',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
