# Generated by Django 4.1.3 on 2023-07-14 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0007_author_user_name_en_us_author_user_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_comment_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='datetime_comment_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_comment_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_comment_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_comment_en_us',
            field=models.TextField(max_length=255, null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_comment_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
    ]
